// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfvqlCmJcomqP-txaCaghVExtcxcaAss',
    appId: '1:467349579093:web:fb3e344a5e9e28e5973bdc',
    messagingSenderId: '467349579093',
    projectId: 'golang-firebase-dae7e',
    authDomain: 'golang-firebase-dae7e.firebaseapp.com',
    storageBucket: 'golang-firebase-dae7e.firebasestorage.app',
    measurementId: 'G-PXZ3YECPEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tmb4lI07Lv72IwYfmKHR1s6L6pGu1mc',
    appId: '1:467349579093:android:fa13b0456fab31dd973bdc',
    messagingSenderId: '467349579093',
    projectId: 'golang-firebase-dae7e',
    storageBucket: 'golang-firebase-dae7e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjfvqlCmJcomqP-txaCaghVExtcxcaAss',
    appId: '1:467349579093:web:890a799ed69633f6973bdc',
    messagingSenderId: '467349579093',
    projectId: 'golang-firebase-dae7e',
    authDomain: 'golang-firebase-dae7e.firebaseapp.com',
    storageBucket: 'golang-firebase-dae7e.firebasestorage.app',
    measurementId: 'G-NHME6VVN7N',
  );
}
